insert into PaymentType (PaymentTypeID, PaymentTypeDescription) values (null, 'suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus');
insert into PaymentType (PaymentTypeID, PaymentTypeDescription) values (null, 'mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel');
insert into PaymentType (PaymentTypeID, PaymentTypeDescription) values (null, 'at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque');
insert into PaymentType (PaymentTypeID, PaymentTypeDescription) values (null, 'vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper');
insert into PaymentType (PaymentTypeID, PaymentTypeDescription) values (null, 'condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque');
insert into PaymentType (PaymentTypeID, PaymentTypeDescription) values (null, 'vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac');
insert into PaymentType (PaymentTypeID, PaymentTypeDescription) values (null, 'semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam');
insert into PaymentType (PaymentTypeID, PaymentTypeDescription) values (null, 'in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus');
insert into PaymentType (PaymentTypeID, PaymentTypeDescription) values (null, 'potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum');
insert into PaymentType (PaymentTypeID, PaymentTypeDescription) values (null, 'pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in');
insert into PaymentType (PaymentTypeID, PaymentTypeDescription) values (null, 'id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate');
insert into PaymentType (PaymentTypeID, PaymentTypeDescription) values (null, 'justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique');
insert into PaymentType (PaymentTypeID, PaymentTypeDescription) values (null, 'interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien');
insert into PaymentType (PaymentTypeID, PaymentTypeDescription) values (null, 'mauris eget massa tempor convallis nulla neque libero convallis eget');
insert into PaymentType (PaymentTypeID, PaymentTypeDescription) values (null, 'orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo');
insert into PaymentType (PaymentTypeID, PaymentTypeDescription) values (null, 'non ligula pellentesque ultrices phasellus id sapien in sapien iaculis');
insert into PaymentType (PaymentTypeID, PaymentTypeDescription) values (null, 'luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce');
insert into PaymentType (PaymentTypeID, PaymentTypeDescription) values (null, 'tortor quis turpis sed ante vivamus tortor duis mattis egestas metus');
insert into PaymentType (PaymentTypeID, PaymentTypeDescription) values (null, 'interdum mauris non ligula pellentesque ultrices phasellus id sapien in');
insert into PaymentType (PaymentTypeID, PaymentTypeDescription) values (null, 'volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse');
insert into PaymentType (PaymentTypeID, PaymentTypeDescription) values (null, 'tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl');
insert into PaymentType (PaymentTypeID, PaymentTypeDescription) values (null, 'ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend');
insert into PaymentType (PaymentTypeID, PaymentTypeDescription) values (null, 'nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus');
insert into PaymentType (PaymentTypeID, PaymentTypeDescription) values (null, 'lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in');
insert into PaymentType (PaymentTypeID, PaymentTypeDescription) values (null, 'rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui');
