insert into RoomCategory (RoomCategoryID, CategoryDescription) values (null, 'nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede');
insert into RoomCategory (RoomCategoryID, CategoryDescription) values (null, 'turpis enim blandit mi in porttitor pede justo eu massa donec');
insert into RoomCategory (RoomCategoryID, CategoryDescription) values (null, 'sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi');
insert into RoomCategory (RoomCategoryID, CategoryDescription) values (null, 'pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis');
insert into RoomCategory (RoomCategoryID, CategoryDescription) values (null, 'scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor');
insert into RoomCategory (RoomCategoryID, CategoryDescription) values (null, 'non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante');
insert into RoomCategory (RoomCategoryID, CategoryDescription) values (null, 'donec odio justo sollicitudin ut suscipit a feugiat et eros');
insert into RoomCategory (RoomCategoryID, CategoryDescription) values (null, 'erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec');
insert into RoomCategory (RoomCategoryID, CategoryDescription) values (null, 'primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec');
insert into RoomCategory (RoomCategoryID, CategoryDescription) values (null, 'curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel');
insert into RoomCategory (RoomCategoryID, CategoryDescription) values (null, 'fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit');
insert into RoomCategory (RoomCategoryID, CategoryDescription) values (null, 'a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur');
insert into RoomCategory (RoomCategoryID, CategoryDescription) values (null, 'dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce');
insert into RoomCategory (RoomCategoryID, CategoryDescription) values (null, 'proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu');
insert into RoomCategory (RoomCategoryID, CategoryDescription) values (null, 'ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer');
insert into RoomCategory (RoomCategoryID, CategoryDescription) values (null, 'eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum');
insert into RoomCategory (RoomCategoryID, CategoryDescription) values (null, 'ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque');
insert into RoomCategory (RoomCategoryID, CategoryDescription) values (null, 'interdum mauris non ligula pellentesque ultrices phasellus id sapien in');
insert into RoomCategory (RoomCategoryID, CategoryDescription) values (null, 'morbi non quam nec dui luctus rutrum nulla tellus in sagittis');
insert into RoomCategory (RoomCategoryID, CategoryDescription) values (null, 'sapien cursus vestibulum proin eu mi nulla ac enim in');
insert into RoomCategory (RoomCategoryID, CategoryDescription) values (null, 'phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate');
insert into RoomCategory (RoomCategoryID, CategoryDescription) values (null, 'nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in');
insert into RoomCategory (RoomCategoryID, CategoryDescription) values (null, 'eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum');
insert into RoomCategory (RoomCategoryID, CategoryDescription) values (null, 'nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat');
insert into RoomCategory (RoomCategoryID, CategoryDescription) values (null, 'id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam');
